using System.Collections.Immutable;
using CsAssay.Catalogue;
using Microsoft.CodeAnalysis;

namespace CsAssay.Analyzers.Tests;

public sealed class AdmissionMatrixTests
{
    private static readonly ImmutableArray<string> FirstAdmissionSlice =
    [
        RuleIds.UnauthorizedSuppression,
        RuleIds.NullableDisabled,
        RuleIds.NullForgiving,
        RuleIds.NullValueIntroduction,
        RuleIds.NullableCoreContract,
        RuleIds.MutableSetter,
        RuleIds.MutableCollectionExposure
    ];

    [Fact]
    public async Task Ide_and_build_execution_modes_agree()
    {
        var sources = AdmissionSources();
        var options = new Dictionary<string, string>();

        var ide = await AnalyzerTestHost.AnalyzeAsync(
            sources,
            options,
            concurrentAnalysis: false);
        var build = await AnalyzerTestHost.AnalyzeAsync(
            sources,
            options,
            concurrentAnalysis: true);

        Assert.Equal(Project(ide), Project(build));
        Assert.All(
            FirstAdmissionSlice,
            ruleId => Assert.Contains(build, diagnostic => diagnostic.Id == ruleId));
    }

    [Fact]
    public async Task Generated_source_remains_visible_to_blocking_rules()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            // <auto-generated/>
            #nullable disable
            using System.Collections.Generic;

            public sealed record GeneratedEnvelope
            {
                public string Value { get; set; } = null!;
                public List<string> Items { get; init; } = [];
            }
            """);

        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == RuleIds.NullableDisabled);
        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == RuleIds.NullForgiving);
        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == RuleIds.NullValueIntroduction);
        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == RuleIds.MutableSetter);
        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == RuleIds.MutableCollectionExposure);
    }

    [Fact]
    public async Task Multi_document_locations_and_generic_contracts_are_stable()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            [
                new AnalyzerSource(
                    "Core/Envelope.cs",
                    """
                    namespace Core;
                    public sealed record Envelope<T>
                        where T : class
                    {
                        public T? Value { get; init; }
                    }
                    """),
                new AnalyzerSource(
                    "Core/Factory.cs",
                    """
                    namespace Core
                    {
                        public static class Factory
                        {
                            public static string Missing() => null!;
                        }
                    }
                    """)
            ],
            new Dictionary<string, string>());

        Assert.Contains(
            diagnostics,
            diagnostic =>
                diagnostic.Id == RuleIds.NullableCoreContract &&
                diagnostic.Location.GetLineSpan().Path == "Core/Envelope.cs");
        Assert.Contains(
            diagnostics,
            diagnostic =>
                diagnostic.Id == RuleIds.NullForgiving &&
                diagnostic.Location.GetLineSpan().Path == "Core/Factory.cs");
        Assert.Contains(
            diagnostics,
            diagnostic =>
                diagnostic.Id == RuleIds.NullValueIntroduction &&
                diagnostic.Location.GetLineSpan().Path == "Core/Factory.cs");
    }

    [Fact]
    public async Task Malformed_documents_do_not_hide_other_document_evidence()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            [
                new AnalyzerSource(
                    "Broken.cs",
                    "public record Broken { public string Value { get; set;"),
                new AnalyzerSource(
                    "Observed.cs",
                    """
                    #nullable disable
                    public sealed class Observed { }
                    """)
            ],
            new Dictionary<string, string>());

        Assert.DoesNotContain(diagnostics, diagnostic => diagnostic.Id == "AD0001");
        Assert.Contains(
            diagnostics,
            diagnostic =>
                diagnostic.Id == RuleIds.NullableDisabled &&
                diagnostic.Location.GetLineSpan().Path == "Observed.cs");
    }

    [Fact]
    public async Task Top_level_and_local_function_null_introduction_is_observed()
    {
        var diagnostics = await AnalyzerTestHost.AnalyzeAsync(
            """
            string Local<T>(T value)
                where T : class
            {
                string Missing() => null;
                return Missing();
            }

            System.Console.WriteLine(Local("value"));
            """);

        Assert.Contains(
            diagnostics,
            diagnostic => diagnostic.Id == RuleIds.NullValueIntroduction);
    }

    private static ImmutableArray<AnalyzerSource> AdmissionSources() =>
    [
        new AnalyzerSource(
            "Core/Policy.cs",
            """
            #pragma warning disable CSAN0002
            #nullable disable
            namespace Core;

            using System.Collections.Generic;

            public sealed record MutableEnvelope
            {
                public string? Name { get; set; } = null!;
                public List<string> Values { get; init; } = [];
            }
            """),
        new AnalyzerSource(
            "Core/Contracts.cs",
            """
            namespace Core
            {
                public static class Contracts
                {
                    public static string? Echo(string? value) => value;
                }
            }
            """)
    ];

    private static string[] Project(ImmutableArray<Diagnostic> diagnostics) =>
        diagnostics
            .Select(diagnostic =>
            {
                var location = diagnostic.Location.GetLineSpan();
                return string.Join(
                    "|",
                    diagnostic.Id,
                    diagnostic.IsSuppressed.ToString(),
                    location.Path,
                    location.StartLinePosition.Line.ToString(
                        System.Globalization.CultureInfo.InvariantCulture),
                    location.StartLinePosition.Character.ToString(
                        System.Globalization.CultureInfo.InvariantCulture),
                    diagnostic.GetMessage(
                        System.Globalization.CultureInfo.InvariantCulture));
            })
            .OrderBy(value => value, StringComparer.Ordinal)
            .ToArray();
}
